services:
  db:
    image: postgres:15
    container_name: jira-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: jira
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: node:20
    container_name: jira-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npx prisma migrate deploy && npm run dev"
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/jira

volumes:
  postgres_data: